public class Program {
    public static void main(String[] args) {
        //OffsetHashTable1();
        //OffsetHashTable2();
        //OffsetHashTable3();

        //ListHashTable1();
        //ListHashTable2();
        //ListHashTable3();
    }


    private static void OffsetHashTable1() {
        HashTable hashTable = new OffsetHashTable(13);

        hashTable.insert( 41);
        hashTable.print();
        System.out.println();
        hashTable.insert( 4);
        hashTable.print();
        System.out.println();
        hashTable.insert( 19);
        hashTable.print();
        System.out.println();
        hashTable.insert( 82);
        hashTable.print();
        System.out.println();
        hashTable.insert( 24);
        hashTable.print();
        System.out.println();
        hashTable.insert( 66);
        hashTable.print();
        System.out.println();
        hashTable.insert( 22);
        hashTable.print();
        System.out.println();
        hashTable.insert( 25);
        hashTable.print();
        System.out.println();
        hashTable.insert( 33);
        hashTable.print();
        System.out.println();
        hashTable.insert( 85);
        hashTable.print();
        System.out.println();
        hashTable.insert( 37);
        hashTable.print();
        System.out.println();
        hashTable.insert( 63);
        hashTable.print();
    }

    private static void OffsetHashTable2() {
        HashTable hashTable = new OffsetHashTable(19);

        hashTable.insert( 50);
        hashTable.print();
        System.out.println();
        hashTable.insert( 99);
        hashTable.print();
        System.out.println();
        hashTable.insert( 30);
        hashTable.print();
        System.out.println();
        hashTable.insert( 79);
        hashTable.print();
        System.out.println();
        hashTable.insert( 23);
        hashTable.print();
        System.out.println();
        hashTable.insert( 64);
        hashTable.print();
        System.out.println();
        hashTable.insert( 22);
        hashTable.print();
        System.out.println();
        hashTable.insert(64);
        hashTable.print();
        System.out.println();
        hashTable.insert(46);
        hashTable.print();
        System.out.println();
        hashTable.insert(64);
        hashTable.print();
        System.out.println();
        hashTable.insert(69);
        hashTable.print();
        System.out.println();
        hashTable.insert(19);
        hashTable.print();
        System.out.println();
        hashTable.insert(88);
        hashTable.print();
        System.out.println();
        hashTable.insert(66);
        hashTable.print();
        System.out.println();
        hashTable.insert(34);
        hashTable.print();
        System.out.println();
        hashTable.remove(19);
        hashTable.print();
        System.out.println();
        hashTable.remove(88);
        hashTable.print();
        System.out.println();
        hashTable.remove(69);
        hashTable.print();
        System.out.println();
        hashTable.remove(34);
        hashTable.print();
        System.out.println();
        hashTable.remove(79);
        hashTable.print();
        System.out.println();
    }

    private static void OffsetHashTable3() {
        HashTable hashTable = new OffsetHashTable(19);

        hashTable.insert( 73);
        hashTable.print();
        System.out.println();
        hashTable.insert( 36);
        hashTable.print();
        System.out.println();
        hashTable.insert( 57);
        hashTable.print();
        System.out.println();
        hashTable.insert( 33);
        hashTable.print();
        System.out.println();
        hashTable.insert( 54);
        hashTable.print();
        System.out.println();
        hashTable.insert( 12);
        hashTable.print();
        System.out.println();
        hashTable.insert( 32);
        hashTable.print();
        System.out.println();
        hashTable.insert( 24);
        hashTable.print();
        System.out.println();
        hashTable.insert( 42);
        hashTable.print();
        System.out.println();
        hashTable.insert( 41);
        hashTable.print();
        System.out.println();
        hashTable.insert( 52);
        hashTable.print();
        System.out.println();
        hashTable.insert( 3);
        hashTable.print();
        System.out.println();
        hashTable.remove( 12);
        hashTable.print();
        System.out.println();
        hashTable.remove( 3);
        hashTable.print();
        System.out.println();
        hashTable.remove( 36);
        hashTable.print();
        System.out.println();
        hashTable.insert( 32);
        hashTable.print();
        System.out.println();
        hashTable.insert( 20);
        hashTable.print();
        System.out.println();
        hashTable.insert( 91);
        hashTable.print();
        System.out.println();
        hashTable.remove( 33);
        hashTable.print();
        System.out.println();
        hashTable.remove( 54);
        hashTable.print();
        System.out.println();
        hashTable.insert( 77);
        hashTable.print();
        System.out.println();
        hashTable.insert( 28);
        hashTable.print();
        System.out.println();
        hashTable.insert( 36);
        hashTable.print();
        System.out.println();
        hashTable.remove( 24);
        hashTable.print();
        System.out.println();
        hashTable.remove( 32);
        hashTable.print();
        System.out.println();
        hashTable.remove( 77);
        hashTable.print();
        System.out.println();
        hashTable.remove( 57);
        hashTable.print();
        System.out.println();
        hashTable.remove( 20);
        hashTable.print();
        System.out.println();
    }

    private static void ListHashTable1() {
        HashTable hashTable = new ListHashTable(13);

        hashTable.insert(66);
        hashTable.print();
        hashTable.insert(69);
        hashTable.print();
        hashTable.insert(52);
        hashTable.print();
        hashTable.insert(25);
        hashTable.print();
        hashTable.insert(69);
        hashTable.print();
        hashTable.insert(9);
        hashTable.print();
        hashTable.insert(29);
        hashTable.print();
        hashTable.insert(4);
        hashTable.print();
        hashTable.insert(82);
        hashTable.print();
        hashTable.insert(60);
        hashTable.print();
        hashTable.insert(6);
        hashTable.print();
        hashTable.insert(66);
        hashTable.print();
    }

    private static void ListHashTable2() {
        HashTable hashTable = new ListHashTable(19);

        hashTable.insert( 69);
        hashTable.print();
        hashTable.insert( 71);
        hashTable.print();
        hashTable.insert( 3);
        hashTable.print();
        hashTable.insert( 84);
        hashTable.print();
        hashTable.insert( 36);
        hashTable.print();
        hashTable.insert( 12);
        hashTable.print();
        hashTable.insert( 44);
        hashTable.print();
        hashTable.insert( 72);
        hashTable.print();
        hashTable.insert( 78);
        hashTable.print();
        hashTable.insert( 65);
        hashTable.print();
        hashTable.insert( 66);
        hashTable.print();
        hashTable.insert( 92);
        hashTable.print();
        hashTable.insert( 2);
        hashTable.print();
        hashTable.insert( 21);
        hashTable.print();
        hashTable.insert( 23);
        hashTable.print();
        hashTable.remove( 69);
        hashTable.print();
        hashTable.remove( 66);
        hashTable.print();
        hashTable.remove( 65);
        hashTable.print();
        hashTable.remove( 84);
        hashTable.print();
        hashTable.remove( 71);
        hashTable.print();
    }

    private static void ListHashTable3() {
        HashTable hashTable = new ListHashTable(19);

        hashTable.insert( 75);
        hashTable.print();
        hashTable.insert( 7);
        hashTable.print();
        hashTable.insert( 51);
        hashTable.print();
        hashTable.insert( 95);
        hashTable.print();
        hashTable.insert( 47);
        hashTable.print();
        hashTable.insert( 19);
        hashTable.print();
        hashTable.insert( 69);
        hashTable.print();
        hashTable.insert( 19);
        hashTable.print();
        hashTable.insert( 1);
        hashTable.print();
        hashTable.insert( 4);
        hashTable.print();
        hashTable.insert( 50);
        hashTable.print();
        hashTable.insert( 90);
        hashTable.print();
        hashTable.remove( 51);
        hashTable.print();
        hashTable.remove( 4);
        hashTable.print();
        hashTable.remove( 90);
        hashTable.print();
        hashTable.insert( 78);
        hashTable.print();
        hashTable.insert( 81);
        hashTable.print();
        hashTable.insert( 29);
        hashTable.print();
        hashTable.remove( 50);
        hashTable.print();
        hashTable.remove( 7);
        hashTable.print();
        hashTable.insert( 23);
        hashTable.print();
        hashTable.insert( 27);
        hashTable.print();
        hashTable.insert( 4);
        hashTable.print();
        hashTable.remove( 19);
        hashTable.print();
        hashTable.remove( 1);
        hashTable.print();
        hashTable.remove( 4);
        hashTable.print();
        hashTable.remove( 78);
        hashTable.print();
        hashTable.remove( 69);
        hashTable.print();
    }
}
